// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyoDaWelbn33DhpGG0dN6r4tUB2W20hZE',
    appId: '1:31297385583:web:a385b46e1206659369499a',
    messagingSenderId: '31297385583',
    projectId: 'quran-app-fe855',
    authDomain: 'quran-app-fe855.firebaseapp.com',
    storageBucket: 'quran-app-fe855.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS9he3BObCCswwxlRi1uEindIbIYoc1Yo',
    appId: '1:31297385583:android:f14dfcc70caa04a369499a',
    messagingSenderId: '31297385583',
    projectId: 'quran-app-fe855',
    storageBucket: 'quran-app-fe855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7z4UU3wpS9YShSXcX3vLMwB1EzrxoEeM',
    appId: '1:31297385583:ios:fd10d4ffabcd18f969499a',
    messagingSenderId: '31297385583',
    projectId: 'quran-app-fe855',
    storageBucket: 'quran-app-fe855.appspot.com',
    iosClientId: '31297385583-86ji2ek62tccs65pamoodcuedguhhk5u.apps.googleusercontent.com',
    iosBundleId: 'com.ziad.dev.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7z4UU3wpS9YShSXcX3vLMwB1EzrxoEeM',
    appId: '1:31297385583:ios:9539dddc4cb97dd469499a',
    messagingSenderId: '31297385583',
    projectId: 'quran-app-fe855',
    storageBucket: 'quran-app-fe855.appspot.com',
    iosClientId: '31297385583-lt33u0kcq9jj9pd928mvhr40o1fhvcgh.apps.googleusercontent.com',
    iosBundleId: 'com.ziad.dev.quranApp.RunnerTests',
  );
}
